# License: Copyright 2021 Amazon Web Services, Inc. or its affiliates.
# All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#    http://aws.amazon.com/apache2.0/
# or in the "license" file accompanying this file.

# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Description: 'This alert will trigger in case of defined expense is reached'

Parameters:
  MyBudget:
      Description: 'Enter a name for this budget'
      Type: String
      Default: 'MyBudget'
  MyAmount:
      Description: 'Enter the cost in dollars to trigger'
      Type: String
      Default: '1000'
  MyPercentage:
      Description: 'Enter the percentage of the threshold to trigger'
      Type: String
      Default: '80'
  MyEmail:
      Description: 'Enter the e-mail to alert'
      Type: String
      Default: 'example@email.com'


Resources:
  Budget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetName: !Ref MyBudget
        BudgetType: COST
        BudgetLimit:
          Amount: !Ref MyAmount
          Unit: USD
        TimeUnit: DAILY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref MyPercentage
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref MyEmail

Metadata: {}
Conditions: {}