AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::LanguageExtensions

Parameters:
  myVPC: 
    Description: Amazon VPCs
    Type: "AWS::EC2::VPC::Id"
  mySubnet: 
    Description: Amazon Subnets
    Type: "AWS::EC2::Subnet::Id"
  mytagvalue: 
    Description: Insert a name for you EC2 Instance - REQUIRED
    Type: "String"
    AllowedPattern: ".+"
  KeyPairName: 
    Description: The Key Pair Name
    Type: "String"
    Default: awsiashojump001
  Environment:
    Description: Lifecycle environment.
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - qa
      - prod
    Default: dev

  LatestAmiId:
    Description: Region-specific image to use.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Mappings:
  dev:
    FirstInstance:
      InstanceType: t2.micro
    SecondInstance:
      InstanceType: t2.micro
    ThirdInstance:
      InstanceType: t2.micro
  qa:
    FirstInstance:
      InstanceType: t2.medium
    SecondInstance:
      InstanceType: t2.medium
    ThirdInstance:
      InstanceType: t2.large
  prod:
    FirstInstance:
      InstanceType: t2.large
    SecondInstance:
      InstanceType: t2.xlarge
    ThirdInstance:
      InstanceType: t2.2xlarge

Resources:
  Fn::ForEach::Instances:
    - InstanceLogicalId
    - [Instance01, Instance02, Instance03]
    - ${InstanceLogicalId}:
        Type: AWS::EC2::Instance
        Properties:
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo "Hello World from $(hostname -f)" > /var/www/html/index.html
          ImageId: !Ref LatestAmiId
          SubnetId: !Ref mySubnet
          InstanceType: !FindInMap
            - !Ref Environment
            - !Ref InstanceLogicalId
            - InstanceType
            - DefaultValue: t2.micro
          Tags:
            - Key: Name
              Value: !Sub ${mytagvalue}-${InstanceLogicalId}
            - Key: InstanceScheduler
              Value: OfficeHours