# WARNING: This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#
# This template will implement AWS services which may have associated cost - USE AT YOUR OWN RISK :-)
#
# AWS Services to be created: DynamoDB table, SNS, Lambda, IAM role, EventBridge
#

AWSTemplateFormatVersion: "2010-09-09"

Description: "Birthday Reminder App with Email Notification on daily basis"

# input parameters

Parameters:

    pSolutionName: 
      Description: The name of this Automation Solution.
      Type: String
      Default: "Birthday-App-Reminder"

    pEmailAddress: 
      Description: The email address for SNS topic notifications.
      Type: String
      Default: "youremail@domain.com"

    pScheduleEvent: 
      Description: The schedule for Lambda function trigger (default run daily at 10AM GMT)
      Type: String
      Default: "cron(0 10 * * ? *)"

    pDynamoDBTable: 
      Description: The name of DynamoDB table for birthday records.
      Type: String
      Default: "BirthdayApp"

    pSampleRecord:
      Description: Create Sample Record in DynamoDB Table (Yes or No)?.
      Default: "Yes"
      Type: String
      AllowedValues:
        - "Yes"
        - "No"
      ConstraintDescription: must specify Yes or No.


Conditions:
  CreateSampleRecord: !Equals [!Ref pSampleRecord, "Yes"]

Resources:


# Create DynamoDB table for birthday App

    rDynamoDBTable: 
      Type: AWS::DynamoDB::Table
      # checkov:skip=CKV_AWS_119: "Encryption not required for DynamoDB Tables"
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W74
              reason: "Encryption Not Required for this PoC solution"
            - id: W28
              reason: "Explicit DB name used in Lambda function"
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "Name"
            AttributeType: "S"
          - 
            AttributeName: "BDate"
            AttributeType: "S"    # format year-month-day e.g "2016-02-15"

        KeySchema: 
          - 
            AttributeName: "Name"
            KeyType: "HASH"
          - 
            AttributeName: "BDate"
            KeyType: "RANGE"

        BillingMode: PAY_PER_REQUEST  #On Demand table (no provisioned capacity)
        DeletionProtectionEnabled: True
        TableName: !Ref pDynamoDBTable
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: True
        Tags: 
            - Key: "cfn-stack-name"
              Value: !Sub ${AWS::StackName}
            - Key: cfn-stack-id
              Value: !Sub ${AWS::StackId}
            - Key: aws-solution
              Value: !Ref pSolutionName

# Create new role for our lambda functions. :- Create new role and attach below policies to it.

    rLambdaRole:
      Type: 'AWS::IAM::Role'
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W28
              reason: "Required for Automation solution"
            - id: W11
              reason: "Required for Automation solution"
            - id: F3
              reason: "Required for Automation solution"
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: "Lambda_Birthday"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Sid: AllowSNStopic
                  Action:
                    - "sns:List*"
                    - "sns:Publish"
                    - "sns:Get*"
                  Resource: !Sub ${rSNSTopic}
                - Effect: Allow
                  Sid: AllowGetOperationsOnDynamoDBTable
                  Action:
                    - "dynamodb:List*"
                    - "dynamodb:DescribeTable"
                    - "dynamodb:Get*"
                    - "dynamodb:Query"
                    - "dynamodb:Scan"
                    - "dynamodb:PutItem"
                  Resource: !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${rDynamoDBTable}
        Tags: 
            - Key: "cfn-stack-name"
              Value: !Sub ${AWS::StackName}
            - Key: cfn-stack-id
              Value: !Sub ${AWS::StackId}
            - Key: aws-solution
              Value: !Ref pSolutionName
            

# Create SNS Topic to send notifications

    rSNSTopic:
        Type: "AWS::SNS::Topic"
        # checkov:skip=CKV_AWS_26: "Encryption not required for SNS topic"
        Metadata:
          cfn_nag:
            rules_to_suppress:
              - id: W47
                reason: "Not Required for Automation solution"
        Properties:
            DisplayName: !Ref pSolutionName
            TopicName: !Ref pSolutionName
            Tags: 
                - Key: "cfn-stack-name"
                  Value: !Sub ${AWS::StackName}
                - Key: cfn-stack-id
                  Value: !Sub ${AWS::StackId}
                - Key: aws-solution
                  Value: !Ref pSolutionName

# Subscribe to SNS Topic to receive notifications

    rMySubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !Ref pEmailAddress
        Protocol: email
        TopicArn: !Ref rSNSTopic

# Create Amazon EventBridge Schedule Lambda On Daily Basis

    rEventsRule:
        Type: "AWS::Events::Rule"
        Properties:
            Name: !Ref pSolutionName
            Description: !Ref pSolutionName
            ScheduleExpression: !Ref pScheduleEvent
            State: "ENABLED"
            Targets: 
              - 
                Arn: !GetAtt rLambdaBirthday.Arn
                Id: "Idd12345678"
            EventBusName: "default"


    rPermissionForEventsToInvokeLambda: 
        Type: AWS::Lambda::Permission
        Properties: 
            FunctionName: !Ref pSolutionName
            Action: "lambda:InvokeFunction"
            Principal: "events.amazonaws.com"
            SourceArn: 
                Fn::GetAtt: 
                    - "rEventsRule"
                    - "Arn"

# Create Lambda Function To Scan DynamoDB table records and send SNS notifications

    rLambdaBirthday:
      Type: AWS::Lambda::Function
    # checkov:skip=CKV_SECRET_6:Strings with a high entropy score are flagged as suspected secrets. Not hardcoded secret
    # checkov:skip=CKV_AWS_117:Lambda VPC not required for this solution
    # checkov:skip=CKV_AWS_173:No sensitive data in Lambda OS variables
    # checkov:skip=CKV_AWS_116:DLQ not required for this solution
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W92
              reason: "Not Required for Automation solution"
            - id: W89
              reason: "Not Required for Automation solution"
      Properties:
        Code:
          ZipFile: |
            import os
            import boto3
            import datetime
            import logging

            # Set up logger
            logger = logging.getLogger()
            logger.setLevel(logging.INFO)

            # Initialize boto3
            dynamodb = boto3.resource('dynamodb')

            def check_birthdays(db_items):
                """
                Checks a list of birthday records and returns a list of birthday information for today and next 5 days.
                """
                today = datetime.date.today()
                birthdays = []
                
                logger.info(f"Starting birthday check for date: {today}")
                birthdays.append(f"Checking today: {today}")
                
                # Check birthdays for today and next 5 days
                for i in range(6):  # 0 to 5 days
                    check_date = today + datetime.timedelta(days=i)
                    check_month_day = str(check_date)[5:]
                    
                    if i == 0:
                        prefix = "TODAY"
                    else:
                        prefix = f"In {i} days"
                        
                    for item in db_items:
                        bday = str(item['BDate'])[5:]
                        birth_year = int(item['BDate'][:4])
                        age = check_date.year - birth_year
                        
                        if bday == check_month_day:
                            if i == 0:
                                message = f"*** Happy birthday 🎉 😊, {item['Name']}! ***"
                                birthdays.append(message)
                                logger.info(f"Found birthday today: {item['Name']}, Age: {age}")
                                birthdays.append(f"Age: {age} years")
                            else:
                                message = f"--- {prefix} ({check_date}): {item['Name']} will turn {age} years ---"
                                birthdays.append(message)
                                logger.info(f"Found upcoming birthday: {item['Name']} on {check_date}")
                
                return birthdays

            def send_sns_notification(account_id, birthdays):
                """
                Sends an SNS notification with the birthday information.
                """
                sns_client = boto3.client('sns')
                
                try:
                    birthday_count = sum(1 for b in birthdays if "birthday" in b.lower() or "will turn" in b.lower())
                    
                    if birthday_count > 0:
                        subject = f"Found {birthday_count} birthday(s) in the next 5 days: Account AWS ID {account_id}"
                        message = "\n".join(birthdays)
                    else:
                        subject = f"No birthdays in the next 5 days: Account AWS ID {account_id}"
                        message = "No birthdays in the next 5 days 😢 " + str(birthdays)
                    
                    logger.info(f"Sending SNS notification with subject: {subject}")
                    
                    # Send the SNS notification
                    sns_client.publish(
                        TargetArn=os.environ["SNS_ARN"],
                        Subject=subject,
                        Message=message
                    )
                    
                    logger.info("SNS notification sent successfully")
                    return ("Process Successfully - " + subject)
                
                except Exception as e:
                    logger.error(f"Failed to send SNS notification: {str(e)}", exc_info=True)
                    return "Failure"

            def lambda_handler(event, context):
                try:
                    logger.info("Starting Lambda execution")
                    
                    # Read AWS Account ID
                    account_id = context.invoked_function_arn.split(":")[4]
                    logger.info(f"Processing for AWS Account ID: {account_id}")

                    # Read environment variables and scan DynamoDB table
                    table_name = os.environ["DB_TABLE"]
                    table = dynamodb.Table(table_name)
                    items = table.scan()['Items']
                    logger.info(f"Retrieved {len(items)} items from DynamoDB table {table_name}")

                    # Check for birthdays
                    birthdays = check_birthdays(items)

                    # Send SNS notification
                    result = send_sns_notification(account_id, birthdays)

                    logger.info(f"Lambda execution completed with result: {result}")
                    return result

                except Exception as e:
                    logger.error("Failed to process Lambda execution", exc_info=True)
                    return "Failure: Check Logs."
                    
        FunctionName: !Ref pSolutionName
        Handler: "index.lambda_handler"
        Timeout: 30
        ReservedConcurrentExecutions: 5
        Architectures:
        - arm64   # Arm-based AWS Graviton2 processors
        Role: !GetAtt "rLambdaRole.Arn"
        Runtime: python3.12
        Environment: 
            Variables:
                SNS_ARN: !Ref rSNSTopic
                DB_TABLE: !Ref pDynamoDBTable
        LoggingConfig:
          LogGroup: !Ref LambdaLogGroup
        Tags: 
            - Key: "cfn-stack-name"
              Value: !Sub ${AWS::StackName}
            - Key: cfn-stack-id
              Value: !Sub ${AWS::StackId}
            - Key: aws-solution
              Value: !Ref pSolutionName

# CW logs group for Lambda function with 7 days retention

    LambdaLogGroup: 
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: !Sub '/aws/lambdas/${pSolutionName}'
        RetentionInDays: 7

# Create Lambda Function To inject sample record into DynamoDB table

    rLambdaSample:
      Type: AWS::Lambda::Function
    # checkov:skip=CKV_SECRET_6:Strings with a high entropy score are flagged as suspected secrets. Not hardcoded secret
    # checkov:skip=CKV_AWS_117:Lambda VPC not required for this solution
    # checkov:skip=CKV_AWS_173:No sensitive data in Lambda OS variables
    # checkov:skip=CKV_AWS_116:DLQ not required for this solution
      Condition: CreateSampleRecord
      DependsOn: rDynamoDBTable
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W92
              reason: "Not Required for Automation solution"
            - id: W89
              reason: "Not Required for Automation solution"
      Properties:
        Code:
          ZipFile: |
            #!/usr/bin/env python3
            import json
            import boto3
            import os
            import cfnresponse

            #Create sample record into DynamoDB table
            def lambda_handler(event,context):

              # logger.info('event: {}'.format(event))
              # logger.info('context: {}'.format(context))
              responseData = {}

              print(f"Event: {event}")

              # Get the request type (CREATE, UPDATE, DELETE)
              request_type = event['RequestType']

              status = cfnresponse.SUCCESS
              
              # Handle the request type

              if request_type == 'Delete':
                  responseData = {'Success': 'Custom Resource removed'}
                  cfnresponse.send(event, context, status, responseData, 'CustomResourcePhysicalID') 

              if request_type == 'Create' or request_type == 'Update':
                  try:
                      dynamodb = boto3.resource('dynamodb')
                      #table name
                      Target=os.environ["DB_TABLE"]
                      table = dynamodb.Table(Target)
                      #inserting values into table
                      response = table.put_item(
                          Item={
                              'Name': 'SampleRecord',
                              'BDate': '2023-02-24'
                              
                          }
                      )
                  except Exception as e:
                      status = cfnresponse.FAILED
                      print(traceback.format_exc())
                      responseData = {'Error': traceback.format_exc(e)}
                  finally:
                      #send event validation to CFN custom resource
                      print("Sending CFN")
                      responseStatus = 'SUCCESS'
                      responseData = {'Success': 'Check Logs.'}
                      cfnresponse.send(event, context, responseStatus, responseData)
                  

        FunctionName: !Sub "${pSolutionName}-sample-record"
        Handler: "index.lambda_handler"
        Timeout: 30
        ReservedConcurrentExecutions: 5
        Role: !GetAtt "rLambdaRole.Arn"
        Runtime: python3.12
        Environment: 
            Variables:
                DB_TABLE: !Ref pDynamoDBTable
        Tags: 
            - Key: "cfn-stack-name"
              Value: !Sub ${AWS::StackName}
            - Key: cfn-stack-id
              Value: !Sub ${AWS::StackId}
            - Key: aws-solution
              Value: !Ref pSolutionName

# Trigger Lambda to create sample record

    CustomResource:
      Type: Custom::LambdaSample
      Condition: CreateSampleRecord
      DependsOn: rLambdaSample
      Properties:
        ServiceToken: !GetAtt "rLambdaSample.Arn"
        ServiceTimeout: 60 # seconds


Outputs:

  oLambdaFunction:
    Description: Lambda Function ARN for Birthday reminders
    Value: !GetAtt rLambdaBirthday.Arn

  oLambdaSampleFunction:
    Condition: CreateSampleRecord
    Description: Lambda Function ARN for Sample Record
    Value: !GetAtt rLambdaSample.Arn

  oSnsTopic:
    Description: SNS Topic ARN for Birthday reminders
    Value: !Ref rSNSTopic

  oDynamoDbTable:
    Description: DynamoDbTable ARN for Birthday reminders
    Value: !GetAtt rDynamoDBTable.Arn


    